// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	FirstName    string
	LastName     string
	Phone        pgtype.Text
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
