// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Amount    int64
	Currency  string
	Status    string
	CreatedAt pgtype.Timestamptz
}
